### ISSUE TITLE
Feedback zweite Runde

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_Rattenfalle.Tanoa#23]
- Schild vom LAV klappt während der Fahrt hoch und runter
- LAV sehr langsam
- Cobra OP? Verlust sollte mehr wehtun (evtl. nur 1 pro Runde)
- Kein NVG im LAV Gunner
- Scope kacke vom Opfor MG (sinnlos, ggf austauschen mit ...?)
- JIP können keine Civs interviewen? (Stefan)
- DeathCam poppt Kaufmenü auf?!
- setMarkerPosLocal für Slingloadmarker
- Zeroing Cobra funzt nicht?
- Zivilfahrzeuge sind auch als Opfor markiert bei Cobra /o\
- TFAR spectator eher setzen
- http://www.rhsmods.org/w/afrfradar#disabling
  `this setVariable ["RHS_Radar_Enabled", false];`

**Comment by McDiod** [comment]
- Flaktruck hat irgendwie 3D Marker auf verbündeten Fahrzeugen
- Subsonic Munition (Opfor FTL) gewollt? Ist nur auf 100m oder so effektiv.
- Kaufmenü hat sich nach der Deathcam geöffnet
- Spieler wurden nicht aus der Respawnwelle entfernt - hab ich im EndGame irgendwann gefixt, muss mal gucken, woran das lag

![20160808201826_1](https://cloud.githubusercontent.com/assets/16549968/17493688/c0c5cdb4-5db1-11e6-9eaf-e09105fc1b3d.jpg)

**Comment by Fusselwurm** [comment]
Ok, hab 'ne neue Meinung zum Thema Tageszeit.

Aus Sicht des Piloten sieht die Welt so aus, daß man (ich) sich während der absoluten Finsternis enorm paranoid bewegt und sich vernünftigerweise nicht traut sich bemerkbar zu machen (außer man is so'n Hallodri wie ich heute) – selbst wenn Leute in der Nähe sind, hat man kaum ne Chance, diese zu identifizieren; und muß aus Sicherheitsgründen (NVG versus "ob ich auf ner Straße bin oder im Feld hör ich an meinen Schritten") ewig weit wegbleiben davon.

Aus Blufor-Sicht wiederum ists vmtl auch eher selbstmörderisch, sich mitten auf ne beleuchtete Kreuzung zu stellen und Halligalli zu machen (wäre aber mal zu testen :trollface: ).

Dh… eigentlich warte ich als Pilot nur auf die Dämmerung, die einsetzen muß bevor ich irgendwelche Spielzüge mache die anderen erlauben mit mir zu interagieren. 
Da der Dschungel enorm dicht ist, und nachts noch beschissener durchsuchbar als tagsüber, kann die andere Seite auch nix anderes tun letztlich als darauf zu warten.

Also mindestens auf Tanoa: Man sollte mit der Morgendämmerung beginnen.

(anders wäre es, wenn es keine NVG gäbe, btw…)

**Comment by DerZade** [comment]
Um auf den AH-1Y einzugehen:
1. Wenn man den AH-1Y nur noch einmal in der ganzen Mission zur Verfügung hat, dann denk bitte dran, irgendetwas zum rearmen hinzustellen.
2. Ich denke, dass es Punkt eins das "OP-Problem" lößt, denn wenn man die Viper richtig einsetzt und ArmA einem keine Strich durch die Rechnung macht, kann man das gleiche wie bei Runde 2 machen ohne abgeschossen zu werden (War Piloten Fehler, da zu tief geflogen)
3. Die beste Lösung meiner Meinung nach wäre, die Viper durch einen bewaffneten Littlebird zu ersetzten (ich bitte um die AH-6M-M, da die nach Erfahrung die Einzigste ist die man auch ohne viel Übung effektiv einsetzten kann) 
4. Wenn Punkt 3 in Kraft tritt, würde ich die AA-Launcher raus nehmen (NICHT die ZSU), da man mit Kleinkalibrigen Waffen genau so gut wenn nicht so gar besser gegen den LB wirken kann
5. Man könnte auch darüber nachdenken die Viper durch eine Bewaffnete Version der UH-1Y zu ersetzten, obwohl es dann halt auch doof ist, da dieser Leute transportieren kann und die M-134 weit nicht so effektiv wie eine 30mm sind.

**Comment by nomisum** [comment]
Ich bin grad etwas verwirrt @DerZade , du meinst sicher AH-1Z rearmen? Dann müssten aber Opfor auch AA nachholen können. Daran mangelte es ihnen in der Mission mehr als uns an Ammo iirc.

Bewaffneter LB find ich auch interessant. Denke AA ist generell schon wichtig, wenn wir nicht auch noch den UH-1Y streichen wollen. Das könnte wiederum zu hart sein, weil der LB zum Angriff tiefer kommen muss... also hat schon weitreichende Änderungen zu Folge, an dessen Ende wieder eine relativ gefahrlose Extraction steht, wenn der Gegner nur ungelenkte Waffen hat.

PS: Ohne Viper würde das Loading Bild falsche Tatsachen suggerieren /o\

**Comment by DerZade** [comment]
> Ich bin grad etwas verwirrt @DerZade , du meinst sicher AH-1Z rearmen?

Ja

> Denke AA ist generell schon wichtig, wenn wir nicht auch noch den UH-1Y streichen wollen.

Du hast recht, dass wenn man die AA raus nimmt nichts mehr gegen den UH-1Y haben. Man könnte dann drüber nach denken statt dieser eine LB reinzubauen aber an sich ist das auch irgendwie ned so geil. 

> Das könnte wiederum zu hart sein, weil der LB zum Angriff tiefer kommen muss...

Solang er ne Missle-Warning hat, wird es gehen müssen.

> also hat schon weitreichende Änderungen zu Folge, an dessen Ende wieder eine relativ gefahrlose 
> Extraction steht, wenn der Gegner nur ungelenkte Waffen hat.

Wie wärs wenn man mal die AA drin lässt und den Attack-LB mal reinmacht, ist ja ned so, dass der keine Countermeassures hat. Natürlich macht es das ganze für den LB schwer aber nicht unmöglich.

> PS: Ohne Viper würde das Loading Bild falsche Tatsachen suggerieren /o\

Ich glaube nicht, dass das dein größtes Problem ist. ^^

**Comment by nomisum** [comment]
umgewandelt in Ticket: https://github.com/gruppe-adler/TvT_Rattenfalle.Tanoa/issues/26
